env:
  REGISTRY: ghcr.io/anthropics/anthropic-quickstarts
name: build
on:
  pull_request:
    paths:
      - .github/**
      - computer-use-demo/**
  push:
    branches:
      - main
    paths:
      - .github/**
      - computer-use-demo/**
jobs:
  build-amd64:
    uses: ./.github/workflows/reusable_build_step.yaml
    with:
      platform: amd64
      builder: ubuntu-latest-16core
      registry: ghcr.io/anthropics/anthropic-quickstarts
      tag_prefix: computer-use-demo-
      context: computer-use-demo
    permissions:
      contents: read
      packages: write
  build-arm64:
    uses: ./.github/workflows/reusable_build_step.yaml
    with:
      platform: arm64
      builder: ubuntu-22.04-arm64-16core
      registry: ghcr.io/anthropics/anthropic-quickstarts
      tag_prefix: computer-use-demo-
      context: computer-use-demo
    permissions:
      contents: read
      packages: write
  merge:
    runs-on: ubuntu-latest
    needs:
      - build-arm64
      - build-amd64
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set image tag
        run: |
          echo "SHORT_SHA=$(git rev-parse --short ${{ github.sha }})" >> "$GITHUB_ENV"
      - name: Create SHA manifest and push
        run: |
          docker buildx imagetools create -t \
            ${REGISTRY}:computer-use-demo-${SHORT_SHA} \
            ${REGISTRY}:computer-use-demo-${SHORT_SHA}-amd64 \
            ${REGISTRY}:computer-use-demo-${SHORT_SHA}-arm64

      - name: Create latest manifest and push
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          docker buildx imagetools create -t \
            ${REGISTRY}:computer-use-demo-latest \
            ${REGISTRY}:computer-use-demo-latest-amd64 \
            ${REGISTRY}:computer-use-demo-latest-arm64
